---
# Source: free5gc/charts/nrf/templates/nrf-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf-nrf
  labels:
    helm.sh/chart: nrf-0.2.2
    app.kubernetes.io/name: nrf
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nrf
      app.kubernetes.io/instance: free5gc
      project: free5gc
      nf: nrf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nrf
        app.kubernetes.io/instance: free5gc
        project: free5gc
        nf: nrf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-mongo
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: mongodb:27017
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the MongoDB; sleep 2; done;"]
      containers:
      - name: nrf
        image: towards5gs/free5gc-nrf:v3.1.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 8000
        command: ["./nrf"]
        args: ["-c", "../config/nrfcfg.yaml"]
        env: 
          - name: DB_URI
            value: mongodb://mongodb/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: nrf-volume
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold:  40
          successThreshold: 1
          httpGet:
            scheme: "HTTP"
            port: 8000
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            scheme: "HTTP"
            port: 8000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: nrf-volume
        projected:
          sources:
          - configMap:
              name: nrf-configmap
