---
# Source: free5gc/charts/udr/templates/udr-configmap.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-configmap
  labels:
    app: free5gc
data:
  udrcfg.yaml: |
    info:
      version: 1.0.1
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: http
        registerIPv4: udr-nudr # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: config/TLS/udr.key
          pem: config/TLS/udr.pem

      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017       
      
      nrfUri: http://nrf-nnrf:8000

    logger:
      MongoDBLibrary:
        ReportCaller: false
        debugLevel: info
      OpenApi:
        ReportCaller: false
        debugLevel: info
      PathUtil:
        ReportCaller: false
        debugLevel: info
      UDR:
        ReportCaller: false
        debugLevel: info
