---
# Source: free5gc/charts/smf/templates/smf-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-smf-smf
  labels:
    helm.sh/chart: smf-0.2.2
    app.kubernetes.io/name: smf
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v3.1.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smf
      app.kubernetes.io/instance: release-name
      project: free5gc
      nf: smf
  template:
    metadata:
      annotations:
        
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n4network-smf",
              "interface": "n4",
              "ips": [ "192.168.1.10/24" ],
              "gateway": [ "192.168.1.1" ]
            }]'
        checksum/config: 552e1e9b07305d3b1c3286acd95607aa1543116b5e1ee7f430ce1c37d87cca0e
      labels:
        app.kubernetes.io/name: smf
        app.kubernetes.io/instance: release-name
        project: free5gc
        nf: smf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']

      containers:
      - name: smf
        image: towards5gs/free5gc-smf:v3.1.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - name: nsmf
          containerPort: 80
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["./smf"]
        args: ["-c", "../config/smfcfg.yaml", "-u", "../config/uerouting.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: smf-volume
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: smf-volume
        projected:
          sources:
          - configMap:
              name: smf-configmap
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml
              - key: uerouting.yaml
                path: uerouting.yaml
